import Head from 'next/head'
import Image from 'next/image'
import golf from '../public/golf.jpg'
import styles from '../styles/Home.module.css'




export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
    
        <h3 className={styles.title}>
          Golf Forever League.
          
        </h3>
       <p> <Image
        
        src={golf}
        alt="golfing"
        width={300}
        height={300}
        
        
       
        ></Image></p>
       
       
          <p><strong>Standings:  </strong> 
           {' '} 
          <code className={styles.code}>Lefties vs Righties 5-1</code>
          </p>
          <p>
          <strong>Referee:</strong>{' '}
          <code className={styles.code}>Phil 3 hits to green clubKiller</code>
          </p>


<section>
        <div className={styles.grid}>
          <a href="https://youtube.com" className={styles.card}>
            <h2>Match Report &rarr;</h2>
            <p>View latest details of team lefties utterly humiliating team Jaqulines.</p>
          </a>

          <a href="https://youtube.com" className={styles.card}>
            <h2>Upcomping Stomp &rarr;</h2>
            <p>Team skins match Wednesday 18:00 Viksberg Righties home shiet turf. </p>
          </a>

        </div>
    </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <code className={styles.code}>Hometeam</code>
        </a>
      </footer>
    </div>
  )
}
