import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import imageLoader from '../components/loader';




export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
    
    
        <h1 className={styles.title}>
          Golf Forever League
          
        </h1>
       <Image
        
        src="/golf.jpg"
        alt="golfing"
        width={300}
        height={300}
        loader={imageLoader}
        
        
       
        />
      
          <p><strong>Standings:</strong> <br/><br/>
           
          <code className={styles.code}>Lefties vs Righties 5-1</code>
          </p>
          
          <p><strong>Referee:  </strong> <br/><br/>
          <code className={styles.code}>Phil (3 to green) ClubKila</code>
          </p>


<section>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Match Report &rarr;</h2>
            <p>View latest details of team lefties utterly humiliating team Jaqulines.</p>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Upcomping stomp &rarr;</h2>
            <p>Team skins match Wednesday 18:00 Viksberg team Righties home turf </p>
          </a>

        </div>
    </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by <strong>&nbsp; TJOG</strong>
          
        </a>
      </footer>
    </div>
  )
}
